# Generated by Django 2.1.2 on 2018-10-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=256, verbose_name='Heading')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
