# Generated by Django 2.1.2 on 2018-10-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertMessage',
        ),
    ]
