# Generated by Django 2.1.2 on 2018-10-12 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=9988500414, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer',
            field=models.BooleanField(default=False, verbose_name='Volunteer'),
        ),
    ]
