# Generated by Django 2.1.2 on 2018-10-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181014_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='incharge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Incharge'),
        ),
    ]
