# Generated by Django 2.1.2 on 2018-10-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_incharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='incharge',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Incharge'),
        ),
    ]
