# Generated by Django 2.1.2 on 2018-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181024_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='lon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Longitude'),
        ),
    ]
